dsccommunity/dsccommunity.org

README.md

* Remove `-1` from example path. 
* Added optionally using HTTPS instead of SSH.
* Wrapping text that was to long.
* Minor changes to git commands.

Update section 'Preparing for a change'

---

content/guidelines/_index.en.md

- Remove section header.
- Removed Slack image that felt inappropriate  in this location (an image on the subject "guideline"s would be more suitable 🤔).
- Updated the text to read better and align with the rest of "Join the converation".

Update to Guidelines ToC

---

.markdownlint.json
content/guidelines/markdown-files.md

Add markdown rule and guide

---

content/Community/contact.en.md

Fixes #13
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/24)

Update Slack link

---

README.md

Closes #15
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/26)

Update Hugo version

---

config.toml

After reading this https://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/ I thought this text would be more suitable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/28)

Update copyright notice

---

config.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/33)

fixing toml for baseURL /

---

config.toml
layouts/partials/head.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/34)

adding google analytics

---

archetypes/blog.md
archetypes/configmgt.md
content/blog/create-an-article.en.md

Added very simple archetype templates for blog & configmgt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/35)

adding archetypes for hugo new cmd

---

content/code_of_conduct/_index.en.md

Add back background color
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/38)

Update Code of Conduct

---

config.toml

This seems to do the trick without breaking things.
Fingers crossed!
fixes #39
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/41)

replacing baseurl to include absolute link for sitemap.xml fixes #39

---

content/community/_index.en.md
content/community/origin-story.md
content/help/_index.en.md
content/help/what-future-for-dsc.md
content/help/what-is-dsc.md

@gaelcolas , @johlju - just some minor proof reading changes. Hopefully nothing too major and isn't changing the meaning at all. Great job you have done!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/43)

Proofing changes

---

archetypes/community_calls.md
content/community_calls/2019-07-31 Notes.en.md
content/community_calls/next_call.en.md

- Fixed archetype to render better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/45)

Add notes for last call and set up next call

---

content/community_calls/_index.en.md
content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/46)

Add agenda entry to next community call

---

data/maintainers.json

- Adds new maintainer that was added to DscResource repo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/47)

Add new maintainer

---

content/community/committee.en.md

@gaelcolas, @johlju - just some minor proof reading changes to the community committee page as well as reducing MD line length - where possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/48)

Minor proof reading changes to committee page

---

content/community_calls/2019-07-31 Notes.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/49)

Add Community Call recording link

---

layouts/_default/list.html
layouts/_default/single.html

Reverts dsccommunity/dsccommunity.org#54
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/55)

Revert "making container fluid to fix #53"

---

content/community_calls/2019-09-11 Notes.en.md
content/community_calls/next_call.en.md

Creating next call and adding last call's notes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/64)

Updating next community call

---

content/blog/dsc-maintenance-windows.en.md
content/blog/how-to-use-dsc-logging.en.md
content/community_calls/2019-09-11 Notes.en.md
themes/dot/assets/css/style.css

- CSS changes to fix
- default List (margin left 15px, list style disk)
- default ordered list (ol: list style numbered)
- consistent font-size with <p> (15px)
- override for nagivagtion list (no margin, 18px font)
- Updating blogs to best leverage those changes and make it more readable
- fixing community call title
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/65)

Fix list format

---

content/guidelines/general.md

*This PR should wait for the PR https://github.com/PowerShell/DscResources/pull/531 to be merged.*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/60)

Update style guideline - how to write empty hashtable

---

content/blog/how-to-use-dsc-logging.en.md

The second file description wasn't indented properly, my bad.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/66)

fixing Yurik's post I broke :)

---

content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/67)

Adding agenda items for community call 2019-10-23

---

content/community_calls/2019-09-11 Notes.en.md
content/community_calls/2019-10-23 Notes.en.md
content/community_calls/next_call.en.md

Hi @dsccommunity/committee,
Could you please review this and merge?
It's creating a new next_call file and making the notes for the last call (includes the VIDEOS!!!).
I should do that more often and be more regular, it could be a great source of info!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/72)

updating weight and adding next call & notes last call

---

data/en/faq.yml

Adding some FAQ entries based on some questions I have had.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/73)

adding FAQ entries incl some for issue #70

---

config.toml

This will make the images reappear.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/78)

Enable markup unsafe mode to use inline html

---

content/blog/convert-a-module-for-continuous-delivery.en.md

*This needs the latest Hugo version to render correctly locally.*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/77)

Add blog "Steps to convert a module for continuous delivery"

---

content/blog/convert-a-module-for-continuous-delivery.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/79)

Update step "Update master branch"

---

content/blog/convert-a-module-for-continuous-delivery.en.md

Extra step to the removal of webhooks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/81)

Convert module blog: Add removal of codegov webhook

---

content/blog/convert-a-module-for-continuous-delivery.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/82)

Update blog simplifying steps

---

content/guidelines/contributing.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/84)

Add verbose log reference

---

content/blog/convert-a-module-for-continuous-delivery.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/85)

Fix typo in blog

---

content/blog/convert-a-module-for-continuous-delivery.en.md

- This updates the `azure-pipelines.yml` with display names to be more aesthetic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/87)

Update azure-pipelines.yml in blog

---

content/blog/convert-a-module-for-continuous-delivery.en.md

Hi,
I've have just that part and noticed, that I kind of shot myself in the leg by deleting the variables required by Invoke-TestSetup functions.
I deleted everything in the header region using search and replace in VSCode without paying attention.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/86)

Unit tests convert instructions

---

content/blog/convert-a-module-for-continuous-delivery.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/91)

Update blog with step to fix links in change log

---

content/blog/convert-a-module-for-continuous-delivery.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/92)

Update blog with ErrorAction on import statement

---

content/blog/convert-a-module-for-continuous-delivery.en.md
content/blog/use-dscresource-common-functions-in-module.en.md
content/styleguidelines/localization.md

- Adds a new blog "DscResource.Common functions in a DSC module"
- Cleans up Localization section. 
Opened up issue #89 to track to further clean up by moving away an entire section that seem more like documentation than style guideline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/90)

Add blog "DscResource.Common functions in a DSC module"

---

content/community_calls/2019-10-23 Notes.en.md
content/community_calls/2019-12-04 Notes.en.md
content/community_calls/_index.en.md
content/community_calls/next_call.en.md
static/ics/dsc_community_call_jan_2020.ics

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/95)

Prepare Next Agenda - Fixes #94

---

content/blog/convert-a-module-for-continuous-delivery.en.md
content/guidelines/maintaining.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/88)

Update to how release is done

---

content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/99)

Add GPRegistryPolicyDsc to agenda

---

content/community/committee.en.md
content/guidelines/administration.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/97)

Add committee member

---

content/guidelines/maintaining.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/103)

Update labels in maintaining guideline

---

content/guidelines/maintaining.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/101)

Updating text around merging

---

content/guidelines/maintaining.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/98)

Adds help around "Skip raising version"

---

content/blog/add-codecov-support-to-repository.md
content/blog/convert-a-module-for-continuous-delivery.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/111)

Add new blog "Add Codecov Support to Repository"

---

content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/118)

updating date to Wednesday 26

---

content/community_calls/2020-01-22 Notes.en.md

Instead of just posting a link, adding the recording as embedded object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/117)

adding video as embeddded object using Hugo syntax

---

content/community_calls/2020-01-22 Notes.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/120)

Added topic to the agenda

---

content/community_calls/next_call.en.md

- Add "Stickers"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/121)

Add agenda item

---

content/community_calls/2020-01-22 Notes.en.md
content/community_calls/next_call.en.md

fixing @raandree's mistakes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/122)

Gaelcolas patch 1

---

content/community_calls/2020-02-26 Notes.en.md
content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/124)

adding todays agenda

---

content/community_calls/2020-01-22 Notes.en.md
content/community_calls/2020-02-26 Notes.en.md
content/community_calls/2020-04-08 Notes.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/125)

adding notes for today

---

content/blog/convert-a-module-for-continuous-delivery.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/127)

Fix correct build worker in blog

---

content/community_calls/2020-04-08 Notes.en.md
content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/129)

Update next community call 2020-05-20

---

content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/130)

Update agenda with releases

---

content/blog/converting-to-pester5-from-the-trenches.md
content/blog/findings-when-coverting-tests-to-pester5.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/133)

Blog: Findings when converting tests to Pester 5

---

content/blog/converting-tests-to-pester5.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/134)

Fix blog title

---

content/blog/dsc-maintenance-windows.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/139)

Fixed typos and links

---

content/community_calls/2020-05-20 Notes.en.md
content/community_calls/next_call.en.md

moving last agenda to notes and updating date for next call
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/137)

updating notes and next call date

---

content/community_calls/next_call.en.md

Added agenda items for July call.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/141)

Update Community Call

---

content/guidelines/administration.md

- This as steps on how to create and connect the maintainer organization team for new repositories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/143)

Update Administration documentation

---

content/community_calls/2020-07-01 Notes.en.md
content/community_calls/next_call.en.md

Agenda for 2020-08-12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/147)

Agenda Community Call August

---

content/community_calls/2020-07-01 Notes.en.md
content/community_calls/2020-08-12 Notes.en.md
content/community_calls/next_call.en.md

This is the first draft of the agenda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/149)

Agenda Next community call 2020 sep

---

content/blog/class-based-dsc-resources.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/151)

Class DSC Only - responding to the GitHub issue proposal.

---

content/community_calls/2020-05-20 Notes.en.md
content/community_calls/2020-07-01 Notes.en.md
content/community_calls/2020-08-12 Notes.en.md
content/community_calls/2020-09-23 Notes.en.md
content/community_calls/next_call.en.md

Updating past community calls with video and setting next call date
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/152)

updating community calls

---

content/guidelines/getting-started.md

Since I put time figuring out this I though we add it to the site instead winding up as a private gist. 🙂
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161)

Added installing GitVersion using release package

---

content/blog/convert-tests-to-pester5-for-dsc-community-repository.md
content/blog/converting-tests-to-pester5.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160)

Blog: Convert tests to Pester 5 for a DSC Community repository

---

content/blog/convert-master-to-main.en.md

Update the blog with the steps needed when GitHub added the function to rename default branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/162)

Update default branch blog

---

content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/165)

adding details in sampler talk

---

content/blog/updating-sampler-github-tasks.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/166)

adding article for GitHub integrations

---

content/blog/add-codecov-support-to-repository.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169)

Update code coverage blog

---

content/blog/add-codecov-support-to-repository.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/170)

Fix code coverage blog - uploading test results

---

content/blog/add-codecov-support-to-repository.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/171)

Revert path in blog

---

content/community_calls/2021-03-10 Notes.en.md
content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/172)

Fix agenda for April

---

content/community_calls/2021-04-21 Notes.en.md
content/community_calls/next_call.en.md

As doom and Manbearpiet reminded me on slack :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/173)

updating dsc community call previous and next

---

content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/174)

adding info about next session on GC Pol

---

content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/175)

Fix agenda

---

content/community_calls/2021-06-02 Notes.en.md
content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/177)

Update agenda for July

---

content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/178)

Update agenda for august

---

content/community_calls/2021-08-25 Notes.en.md
content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/179)

Fix agenda October 2021

---

azure-pipelines.yml
content/community_calls/2021-08-25 Notes.en.md
content/community_calls/2021-10-06 Notes.en.md
content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/180)

Update Agenda November 2021

---

content/community_calls/2021-11-17 Notes.en.md
content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/182)

Update agenda for Feb 9th

---

content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/184)

@johlju Update agenda for Febrary 16th call

---

layouts/resources/list.html

…o master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/192)

adding azdo task to generate resources json

---

content/community_calls/2022-05-04 Notes.en.md
content/community_calls/next_call.en.md
data/resources.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/194)

updating last call notes and info for next DSC community call

---

content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/196)

Update agenda for 27th July

---

content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/199)

Fix releases

---

content/community_calls/2022-09-07 Notes.en.md
content/community_calls/next_call.en.md

October 19
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/202)

updating next call

---

content/community_calls/2022-10-19 Notes.en.md
content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/204)

Fix agenda November 2022

---

content/community_calls/2022-11-30 Notes.en.md
content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/205)

Fix agenda for January 11th

---

content/community_calls/2023-01-11 Notes.en.md
content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/208)

Fix agenda february 2023

---

content/guidelines/contributing.md
content/guidelines/getting-started.md

- Updating to new default branch name `main`.
- Adding quick-steps for contributors to easily clone a repo
- Adding additional help to install various components using `winget`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/209)

Updating contributing guidelines

---

content/community_calls/2023-01-11 Notes.en.md
content/community_calls/2023-02-22 Notes.en.md
content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/210)

Fix agenda April 2023

---

content/community_calls/2023-08-09 Notes.en.md
content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/212)

August call

---

content/community_calls/2023-09-20 Notes.en.md
content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/215)

adding changes for next Community call

---

content/community_calls/next_call.en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/216)

Fix releases in agenda

---

azure-pipelines.yml
content/blog/convert-a-module-for-continuous-delivery.en.md
content/blog/convert-master-to-main.en.md
content/blog/updating-sampler-github-tasks.md
content/guidelines/testing-guidelines.md
layouts/_default/single.html
layouts/community/maintainers.html
layouts/partials/head.html

Fix #219
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/220)

Fix Hugo website to work on v0.135.0

---

.devcontainer/Dockerfile
azure-pipelines.yml
config.toml

This PR address #223
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/224)

Fix Hugo v0.136+ deprecation warnings

---

content/guidelines/contributing.md

Addresses #218 and some spelling fixes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/225)

Clarify merge conflict with new article

---

content/community_calls/2023-11-02 Notes.en.md
content/community_calls/2024-03-19 Notes.en.md
content/community_calls/2024-04-19 Notes.en.md
content/community_calls/2024-05-29 Notes.en.md
content/community_calls/2024-08-26 Notes.en.md
content/community_calls/2024-10-11 Notes.en.md
content/community_calls/2024-11-14 Notes.en.md

This PR adds the latest community calls from YouTube.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/226)

Add latest DSC community calls from YouTube

---

content/community_calls/2025-02-06 Notes.en.md
content/community_calls/next_call.en.md

Adds the community call from the 7th of February. Also added the next ones in the next_call.en.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/227)

Add latest community call

---

content/community_calls/2025-02-06 Notes.en.md
content/community_calls/2025-03-29 Notes.en.md

This PR addresses a minor fix for February's community call URL and adds the March edition.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/229)

Update community call march

---

content/community_calls/2025-06-11 Notes.en.md

This PR adds the meeting notes of DSC's community call in June.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/235)

Add notes for June

---

content/blog/what-is-microsoft-dscv3.md

Added a new article written by @johlju and slightly cleaned up by me :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/241)

Add new article what is Microsoft DSC v3

---

content/blog/what-is-microsoft-dscv3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/245)

Fix link in blog article

---

content/community_calls/2025-06-11 Notes.en.md
content/community_calls/2025-09-07 Notes.en.md

This pull request adds the meeting notes for the September community call.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/246)

Add notes for September
